### ISSUE TITLE
Multiple loggers, file/line,tid metadata (was: Great tool)

### ISSUE THREAD

**Issue by jackyjia** [Morgan-Stanley/binlog#2]
Hi, thanks for open sourcing this tool, bringing the logging framework used in low-latency trading system to the public.

Had a quick look at existing features, any plan to support below two features?

1. multiple loggers in the same process: we want to separate logs of peripheral threads from critical thread. spdlog enables us to create multiple loggers. How is it supported in binlog?
1. usage sugar, for example, spdlog's SPDLOG_INFO will log the file name, line number, tid etc.

Thanks!

**Comment by erenon** [comment]
Hi, thanks for your interest.

1. Multiple loggers are supported. There are two kinds of separation: session level and session writer level. I suppose your goal is to write logs from different threads to different logfiles, right?
In this case, you need two sessions:

    binlog::Session critical_session;
    binlog::SessionWriter critical_session_writer(critical_session);

    BINLOG_INFO_W(critical_session_writer, "log from critical thread");

    critical_session.consume(critical_thread_log_ostream);

This can be duplicated for each thread.
More on this: http://binlog.org/UserGuide.html#a-more-elaborate-greeting-of-the-world

2. Binlog also saves file full path, line number, function name, as static data. You can customize the generated log appearance using `bread -f`, see `bread -h` for help. Thread id is modeled as writer name, described here: http://binlog.org/UserGuide.html#named-writers

**Comment by jackyjia** [comment]
> Hi, thanks for your interest.
> 
> 1. Multiple loggers are supported. There are two kinds of separation: session level and session writer level. I suppose your goal is to write logs from different threads to different logfiles, right?
>    In this case, you need two sessions:
>    ```
>     binlog::Session critical_session;
>     binlog::SessionWriter critical_session_writer(critical_session);
>    
>     BINLOG_INFO_W(critical_session_writer, "log from critical thread");
>    
>     critical_session.consume(critical_thread_log_ostream);
>    ```
> 
> This can be duplicated for each thread.
> More on this: http://binlog.org/UserGuide.html#a-more-elaborate-greeting-of-the-world
> 
> 1. Binlog also saves file full path, line number, function name, as static data. You can customize the generated log appearance using `bread -f`, see `bread -h` for help. Thread id is modeled as writer name, described here: http://binlog.org/UserGuide.html#named-writers

Thanks for the quick reply. Another question from the team: how is log rotation supported? Didn't find it in user's guide.

**Comment by erenon** [comment]
Log rotation is not supported right now, but not too difficult to add. See #3 for tracking.

**Comment by loveyoupeng** [comment]
How about log the same content within the same session to multiple destinations? 
Basically similar to what logback have done with multiple appenders, it will be better to provide plugin/extension pointer to implement customizable log destinations. e.g. sending log to file, console and monitoring agents at the same time

**Comment by erenon** [comment]
@loveyoupeng : it is definitely doable, requires two separate things:

  1. A `MultiOutputStream`, that models the [mserialize::OutputStream](http://binlog.org/Mserialize.html#outputstream) concept, and simply forwards every write call to the wrapped streams. See #4 for tracking.

   2. For sending to the console, a `TextOutputStream`, that receives binlog payload, converts it to text and writes it to a given ostream. See #5 for more.

**Comment by erenon** [comment]
Fixed by #17 and #15

**Comment by valmirnjr** [comment]
Hi @erenon, suppose that I need to log messages from a class constructor and each class should have its own output file. What's the recommended way to do it? 
I tried creating a Session, a SessionWriter, and a different output stream for each class. Then, I used BINLOG_CREATE_SOURCE_AND_EVENT. The event metadata was put only in the first constructed class (the next ones have an eventSource id different from 0) and that makes bread crash.

**Comment by erenon** [comment]
Hi @valmirnjr. iiuc, you want to send events, coming from a single event source (a set of such sources), to different sinks (files), based on the SessionWriter instance being used. I don't think it is trivially achievable, as Binlog was not designed with this use-case in mind. Having a dynamic number of output files sounds challenging to me, from the operations point of view. Out of interest, can you tell me more about your use-case?

I can imagine the following solutions:

(1) If your project is linux only, the `hiperf` branch accidentally makes your solution (1 Session and SessionWriter/instance) work. The `hiperf` implementation stores event source ids statically, instead of assigning them runtime. See the limitations of the high performance branch here: https://github.com/morganstanley/binlog/blob/hiperf/doc/UserGuide.md#limitations

(2) Change the `binlog::Session` type to store the metadata in a common (global?) storage, instead of in the session object.

(3) Instead of separating data at the writer level, create an EventFilter, that filters events based on their content/writer id. EventFilter example: https://github.com/morganstanley/binlog/blob/main/include/binlog/EventFilter.hpp (this is something different, but can illustrate the idea). This can be used together with a multi output stream, to achieve your goal: http://binlog.org/UserGuide.html#multiple-output

>  that makes bread crash

Did `bread` really crash? (terminating with a caught exception does not count) If yes, please file a different ticket with a repro. bread is not supposed to crash, ever. thanks.
