### ISSUE TITLE
C-strings support

### ISSUE THREAD

**Issue by StarOrpheus** [Morgan-Stanley/binlog#54]
I've noticed that `char*` is understood as a pointer to char, but not as common c-string `char const*`.
For example, `strerror(int)` function returns a `char*` string.
I would consider this as a bug, but not a feature request.

**Comment by erenon** [comment]
Thanks for reporting. For the reference, here's how `const char*` is supported (and treated as a string): https://github.com/Morgan-Stanley/binlog/blob/master/include/binlog/const_char_ptr_is_string.hpp
The comment includes the rational. This is already a trade-off. Treating `char*` the same way could result in serious bugs, e.g:

```
char carray[] = {1,2,3};
char* parray = carray;
BINLOG_INFO("{}", parray); // if char* were treated as a string, this would be UB
```

Because the language mixes strings and pointers, I don't see a way to resolve this, that is both convenient and always correct. Ideas are welcome!

`strerror` is especially troubling, because the use case you are presenting is pretty valid. Here's a workaround for now:

```
const char* cstrerror(int e) { return std::strerror(e); } // note the const char* return value
BINLOG_INFO("{}", cstrerror(EBADF));
// Outputs: Bad file descriptor
```

A different workaround is to cast the return value to const, or to wrap it with `string_view`:

```
BINLOG_INFO("{}", string_view(strerror(EBADF)));
```

**Comment by StarOrpheus** [comment]
@erenon Thanks for the fast reply. Imagine this code:
```
char c = 5;
std::cout << c;
```
What will you get? `char` is a special type and often treated specially. Same for `char*`:
```
char* s = (char*) "keke";
std::cerr << s;
``` 
Will print a "keke" string.
Acting like `std::ostream`  is more friendly, isn't it?

**Comment by erenon** [comment]
```
char c = 5;
std::cout << c;
```
On my platform, this will "print" a non-printable character. Also consider this:

```
int8_t c = 99;
std::cout << c;
```
It will print `c`. Not quite intuitive to me. What about this: I can add a header, `binlog/char_ptr_is_string.hpp`, that will make Binlog treat `char*` objects as strings, but clients have to include it explicitly, to remain on the safe side by default.
Would that be an acceptable solution for you?

**Comment by StarOrpheus** [comment]
@erenon (about code samples) That's right what I mean. `char` is treated specially by `ostream`s, not just like any other integer type.
Can you please make a macro for that, like ENABLE_CHAR_PTR_AS_STR_SUPPORT or so? It's easier including two headers instead of one is more complicated, and one of them can be occasionally omitted.

**Comment by erenon** [comment]
Such a macro can yield to confusion, e.g: if one header defines it, and the other does not: depending on the order, the macro will or will not take effect.
Experience shows that larger projects will have their own log header anyway (for custom log macros, categories, adoption for types and enums, preprocessor control of verbosity, etc), therefore the inclusion of the Binlog headers will be centralized.

**Comment by StarOrpheus** [comment]
I was thinking about it like a project-defined macro.
OK then, your solution is great too. 
Also thank you for the work you do, already using it in my project (currently private) and fully satisfied with it!
