### ISSUE TITLE
Request: Standardise default bread timestamp

### ISSUE THREAD

**Issue by andrewkcorcoran** [Morgan-Stanley/binlog#60]
Having the default timestamp be in American month/day format and missing the year is a bit confusing. It's also unclear which timezone the logs refer to. Perhaps the default output should be ISO 8601 or similar standardised format?

**Comment by erenon** [comment]
Here are the possible alternatives I can think of:

```
03/26 09:39:04.368615777
03-26 09:39:04.368615777
2020-03-26 09:39:04.368615777
2020-03-26 09:39:04.368615777
2020-03-26 09:39:04.368615777+01:00
```

Some of these resemble to ISO 8601 format, with the difference that the date-time separator `T` is replaced by ` `, because the former ins unreadable to me, and nanosecond precision is used.
The current format (the first one) was choose because of brevity. Having `2020-` displayed repeatedly seems to me a waste of resources and screen estate: it only adds noise, and if needed, still can be added via the `-d` switch.

Which one do you prefer and why?

**Comment by andrewkcorcoran** [comment]
The use case I'm thinking of is that people are setting up a T+1 process to convert the binary logs to human readable and archive them. I can see this being quite common and therefore I would have thought outputting all possible information should be the default so my preference would be for the lat option.

**Comment by erenon** [comment]
To be lossless, we archive the binary logs themselves (e.g: think about float values or pretty printed types [not yet introduced to the open source version]).

If we consider a cronjob task that needs to be setup once, I don't think it is a big deal to provide additional arguments (`-d "%Y-%m-%d %H:%M:%S.%U %z"` in this case) to achieve the desired output.

I'd rather focus on the interactive use-case, and set the defaults the most useful way for users entering "$ bread app.blog".
