### ISSUE TITLE
Feature request: structural logging interface

### ISSUE THREAD

**Issue by fdrex** [Morgan-Stanley/binlog#73]
Structural logging is more friendly to programs. With tags encodes the structual information and binlogs contains the value, it's possible and easy to convert binlogs to json (or other data formats), which is more suitable for further processing by other people.

It's best to have an interface like:
```
LOG({'key1', Value1}, {'key2', Value2}, ...);
```

Is it possible?

**Comment by erenon** [comment]
I'm not sure if I understand to proposed feature entirely. What's the
expected output of that LOG interface?

**Comment by fdrex** [comment]
I've adapt the code to fit my need. The following adapted code (test/integration/LoggingContainers.cpp) shows the interface:

```
#include <binlog/binlog.hpp>

#include <iostream>

#include <array>
#include <deque>
#include <forward_list>
#include <list>
#include <map>
#include <set>
#include <vector>

int main()
{
  // Standard containers

  //[sequence
  std::vector<int>       vec{1,2,3};
  std::array<int, 3>     arr{4,5,6};
  std::forward_list<int> lst{7,8,9};
  BINLOG_INFO("vec,arr,lst", vec, arr, lst);
  // Outputs: {"arr":[4,5,6],"lst":[7,8,9],"vec":[1,2,3]}
  //]

  std::deque<int> deq{1,2,3};
  std::list<int> list{4,5,6};
  std::vector<bool> vb{true, false, true};
  BINLOG_INFO("deq,list,vb", deq, list, vb);
  // Outputs: {"deq":[1,2,3],"list":[4,5,6],"vb":[true,false,true]}

  BINLOG_INFO("ev,el", std::vector<int>{}, std::list<bool>{});
  // Outputs: {"el":[],"ev":[]}

  //[associative
  std::set<int> set{4,8,15,16,23,42};
  std::map<char, std::string> map{{'a', "alpha"}, {'b', "beta"}};
  BINLOG_INFO("set,map", set, map);
  // Outputs: {"map":[["a","alpha"],["b","beta"]],"set":[4,8,15,16,23,42]}
  //]

  std::multiset<int> ms{1,2,2,3,1};
  std::multimap<int, char> mm{{1, 'a'}, {1, 'b'}, {2, 'c'}};
  BINLOG_INFO("ms,mm", ms, mm);
  // Outputs: {"mm":[[1,"a"],[1,"b"],[2,"c"]],"ms":[1,1,2,2,3]}

  // unordered_set and map cannot be tested this way,
  // since the order of the elements is not specified.

  //[carray
  int array[] = {1, 2, 3};
  BINLOG_INFO("Array", binlog::array_view(array, 3));
  // Outputs: {"Array":[1,2,3]}
  //]


  return 0;
}

```

**Comment by fdrex** [comment]
Basically, the format-string is changed to "keys", and the parameters is changed to "values". The bread outputs json only. Thus it is very machine friendly for future processing.

**Comment by fdrex** [comment]
The "Outputs" above only shows the parameter values (for unit test purpose). Actually, the whole output is like:
{
  'timestamp': time_in_nano,
  'source': {<a lot of fields> },
  'event': {<key-values>},
}

**Comment by erenon** [comment]
Thanks for the detailed idea.
The format string of the log macro must adhere current requirements: one placeholder for each argument. Otherwise components using this idea would be incompatible components using the original macros. Something like this could work:

```
BINLOG_INFO("foo: {} bar: {}", foo, bar);
```

While it looks a bit more verbose, it is actually not too difficult to create a macro:

```
LOG(foo, bar)
```

that expands to the above. The keys of the JSON object will be the names of the variables.

This is for producing log events that has the "key: {}" format. To actually produce JSON, one would need to add a new printer to `printers.cpp`, or even, a new binary (e.g: `b2json`), that converts the log events to JSON. It'd take a different PrettyPrinter and ToStringVisitor. Special care must be taken to escape special chars as required by the JSON specification.
